version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Shanghai
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: daily
      timezone: Asia/Shanghai
