name: Flutter Android
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: |
          cd android
          mkdir key
          echo ${{ secrets.KEY }} | base64 --decode >> key/nexttest.jks
          echo ${{ secrets.PROPERTIES }} | base64 --decode >> key.properties
          flutter pub get
          flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v3
        with:
          name: NextTest-Android-arm64-v8a
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: NextTest-Android-armeabi-v7a
          path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: NextTest-Android-x86_64
          path: build/app/outputs/apk/release/app-x86_64-release.apk