name: Flutter Android
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: |
          flutter pub get
          flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v3
        with:
          name: Apk
          path: build/app/outputs/apk/release/