name: Flutter Windows
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          cache: true
      - run: |
          flutter config --enable-windows-desktop
          flutter build windows
      - uses: actions/upload-artifact@v3
        with:
          name: NextTest-Windows
          path: build/windows/runner/Release/